In [2]:
import numpy as np

matrice_originale = [[1, 1, 1, 1], [5, 1, 1, 1], [20, -4, 0, 42]]

ndarray_creato = np.empty((3, 4), dtype=int)

for i in range(3):
    for j in range(4):
        ndarray_creato[i, j] = matrice_originale[i][j]


print(ndarray_creato)


[[ 1  1  1  1]
 [ 5  1  1  1]
 [20 -4  0 42]]
