In [4]:
import numpy as np

array_originale = np.array([[10, 22, 21, 8, 9],
                            [9, 42, 3, 18, 11],
                            [5, 4, 30, 12, 29],
                            [37, 31, 7, 2, 26],
                            [8, 6, 4, 33, 15]])

valore_minimo = np.min(array_originale)
valore_massimo = np.max(array_originale)

array_trasformato = (array_originale - valore_minimo) / (valore_massimo - valore_minimo)

print("Array originale:")
print(array_originale)

print("\nArray trasformato:")
print(array_trasformato)


Array originale:
[[10 22 21  8  9]
 [ 9 42  3 18 11]
 [ 5  4 30 12 29]
 [37 31  7  2 26]
 [ 8  6  4 33 15]]

Array trasformato:
[[0.2   0.5   0.475 0.15  0.175]
 [0.175 1.    0.025 0.4   0.225]
 [0.075 0.05  0.7   0.25  0.675]
 [0.875 0.725 0.125 0.    0.6  ]
 [0.15  0.1   0.05  0.775 0.325]]
